### ISSUE TITLE
Can XDF XML have custom fields?

### ISSUE THREAD

**Issue by abcsds** [cbrnr/XDF.jl#5]
My question goes towards whether or not we should just keep the whole XML header and footer as a string in the stream dictionary. This would only be helpful in case the file contains custom fields.

**Comment by cbrnr** [comment]
Yes, the XML can contain custom fields, so we should make headers and footers available somehow. In addition, the standardized part could of course be transformed into a more accessible data structure.

**Comment by abcsds** [comment]
This issue was closed with pr #4.
